
export const iconsSkills = {
  Html: "/skills/html.svg",
  Css: "/skills/css.svg",
  Javascript: "/skills/javascript.svg",
  Typescript: "/skills/typescript.svg",
  NodeJS: "/skills/nodejs.svg",
  VueJs: "/skills/vue-js.svg",
  Vite: "/skills/vite.svg",
  ReactJS: "/skills/react.svg",
  ExpressJS: "/skills/expressjs.svg",
  TailwindCSS: "/skills/tailwindcss.svg",
  NextJS: "/skills/next.svg",
  MongoDB: "/skills/mongodb.svg",
  Git: "/skills/git.png",
  Expo: "/skills/expo.png",
  Swift: "/skills/swift.svg",
  SwiftUI: "/skills/swiftui.png",
  Supabase: "/skills/supabase.svg",
};
